### ISSUE TITLE
What's the license of this code?

### ISSUE THREAD

**Issue by f-dangel** [pvjosue/pytorch_convNd#3]
Hi,

I would like to use this code for a project licensed as MIT (this repository would be a `git submodule` in that project). Since there is no declaration via a `LICENSE` file in the repo, I was wondering if you could clarify the copyright of this repository.

Best,
Felix

**Comment by pvjosue** [comment]
Hey, 
Good point, I'll add an mit license, feel free to use the repo.
Cheers

**Comment by f-dangel** [comment]
Great, thanks a lot!
